# version of mixin to use
mixinVersion: 1.4.0
targetNamespace: ""
dashboards:
  annotations: {}
  labels:
    grafana_dashboard: "1"
rules:
  deploy: true
  flavour: "victoriametrics"
grafana:
  folder: "Kubernetes Mixin Dashboards" # options: "prometheus", "victoriametrics"